server:
  port: 8103  #运行端口号
spring:
  application:
    name: eureka-client #服务名称
eureka:
  client:
    register-with-eureka: true  #注册到Eureka的注册中心
    fetch-registry: true  #获取注册实例列表
    service-url:
      defaultZone: http://zgpeace:123456@localhost:8004/eureka/  #配置注册中心地址
